//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"

	v1beta1 "github.com/projectsveltos/addon-controller/api/v1beta1"
	apiv1alpha1 "github.com/projectsveltos/libsveltos/api/v1alpha1"
	apiv1beta1 "github.com/projectsveltos/libsveltos/api/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Chart)(nil), (*v1beta1.Chart)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Chart_To_v1beta1_Chart(a.(*Chart), b.(*v1beta1.Chart), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Chart)(nil), (*Chart)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Chart_To_v1alpha1_Chart(a.(*v1beta1.Chart), b.(*Chart), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterConfiguration)(nil), (*v1beta1.ClusterConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterConfiguration_To_v1beta1_ClusterConfiguration(a.(*ClusterConfiguration), b.(*v1beta1.ClusterConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterConfiguration)(nil), (*ClusterConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterConfiguration_To_v1alpha1_ClusterConfiguration(a.(*v1beta1.ClusterConfiguration), b.(*ClusterConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterConfigurationList)(nil), (*v1beta1.ClusterConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterConfigurationList_To_v1beta1_ClusterConfigurationList(a.(*ClusterConfigurationList), b.(*v1beta1.ClusterConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterConfigurationList)(nil), (*ClusterConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterConfigurationList_To_v1alpha1_ClusterConfigurationList(a.(*v1beta1.ClusterConfigurationList), b.(*ClusterConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterConfigurationStatus)(nil), (*v1beta1.ClusterConfigurationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterConfigurationStatus_To_v1beta1_ClusterConfigurationStatus(a.(*ClusterConfigurationStatus), b.(*v1beta1.ClusterConfigurationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterConfigurationStatus)(nil), (*ClusterConfigurationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterConfigurationStatus_To_v1alpha1_ClusterConfigurationStatus(a.(*v1beta1.ClusterConfigurationStatus), b.(*ClusterConfigurationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterProfile)(nil), (*v1beta1.ClusterProfile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterProfile_To_v1beta1_ClusterProfile(a.(*ClusterProfile), b.(*v1beta1.ClusterProfile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterProfile)(nil), (*ClusterProfile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterProfile_To_v1alpha1_ClusterProfile(a.(*v1beta1.ClusterProfile), b.(*ClusterProfile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterProfileList)(nil), (*v1beta1.ClusterProfileList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterProfileList_To_v1beta1_ClusterProfileList(a.(*ClusterProfileList), b.(*v1beta1.ClusterProfileList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterProfileList)(nil), (*ClusterProfileList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterProfileList_To_v1alpha1_ClusterProfileList(a.(*v1beta1.ClusterProfileList), b.(*ClusterProfileList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterProfileResource)(nil), (*v1beta1.ClusterProfileResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterProfileResource_To_v1beta1_ClusterProfileResource(a.(*ClusterProfileResource), b.(*v1beta1.ClusterProfileResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterProfileResource)(nil), (*ClusterProfileResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterProfileResource_To_v1alpha1_ClusterProfileResource(a.(*v1beta1.ClusterProfileResource), b.(*ClusterProfileResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterReport)(nil), (*v1beta1.ClusterReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterReport_To_v1beta1_ClusterReport(a.(*ClusterReport), b.(*v1beta1.ClusterReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterReport)(nil), (*ClusterReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterReport_To_v1alpha1_ClusterReport(a.(*v1beta1.ClusterReport), b.(*ClusterReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterReportList)(nil), (*v1beta1.ClusterReportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterReportList_To_v1beta1_ClusterReportList(a.(*ClusterReportList), b.(*v1beta1.ClusterReportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterReportList)(nil), (*ClusterReportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterReportList_To_v1alpha1_ClusterReportList(a.(*v1beta1.ClusterReportList), b.(*ClusterReportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterReportSpec)(nil), (*v1beta1.ClusterReportSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterReportSpec_To_v1beta1_ClusterReportSpec(a.(*ClusterReportSpec), b.(*v1beta1.ClusterReportSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterReportSpec)(nil), (*ClusterReportSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterReportSpec_To_v1alpha1_ClusterReportSpec(a.(*v1beta1.ClusterReportSpec), b.(*ClusterReportSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterReportStatus)(nil), (*v1beta1.ClusterReportStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterReportStatus_To_v1beta1_ClusterReportStatus(a.(*ClusterReportStatus), b.(*v1beta1.ClusterReportStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterReportStatus)(nil), (*ClusterReportStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterReportStatus_To_v1alpha1_ClusterReportStatus(a.(*v1beta1.ClusterReportStatus), b.(*ClusterReportStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterSummary)(nil), (*v1beta1.ClusterSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterSummary_To_v1beta1_ClusterSummary(a.(*ClusterSummary), b.(*v1beta1.ClusterSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterSummary)(nil), (*ClusterSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterSummary_To_v1alpha1_ClusterSummary(a.(*v1beta1.ClusterSummary), b.(*ClusterSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterSummaryList)(nil), (*v1beta1.ClusterSummaryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterSummaryList_To_v1beta1_ClusterSummaryList(a.(*ClusterSummaryList), b.(*v1beta1.ClusterSummaryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterSummaryList)(nil), (*ClusterSummaryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterSummaryList_To_v1alpha1_ClusterSummaryList(a.(*v1beta1.ClusterSummaryList), b.(*ClusterSummaryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterSummarySpec)(nil), (*v1beta1.ClusterSummarySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterSummarySpec_To_v1beta1_ClusterSummarySpec(a.(*ClusterSummarySpec), b.(*v1beta1.ClusterSummarySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterSummarySpec)(nil), (*ClusterSummarySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterSummarySpec_To_v1alpha1_ClusterSummarySpec(a.(*v1beta1.ClusterSummarySpec), b.(*ClusterSummarySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterSummaryStatus)(nil), (*v1beta1.ClusterSummaryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterSummaryStatus_To_v1beta1_ClusterSummaryStatus(a.(*ClusterSummaryStatus), b.(*v1beta1.ClusterSummaryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterSummaryStatus)(nil), (*ClusterSummaryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterSummaryStatus_To_v1alpha1_ClusterSummaryStatus(a.(*v1beta1.ClusterSummaryStatus), b.(*ClusterSummaryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Clusters)(nil), (*v1beta1.Clusters)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Clusters_To_v1beta1_Clusters(a.(*Clusters), b.(*v1beta1.Clusters), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Clusters)(nil), (*Clusters)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Clusters_To_v1alpha1_Clusters(a.(*v1beta1.Clusters), b.(*Clusters), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DryRunReconciliationError)(nil), (*v1beta1.DryRunReconciliationError)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DryRunReconciliationError_To_v1beta1_DryRunReconciliationError(a.(*DryRunReconciliationError), b.(*v1beta1.DryRunReconciliationError), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DryRunReconciliationError)(nil), (*DryRunReconciliationError)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DryRunReconciliationError_To_v1alpha1_DryRunReconciliationError(a.(*v1beta1.DryRunReconciliationError), b.(*DryRunReconciliationError), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Feature)(nil), (*v1beta1.Feature)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Feature_To_v1beta1_Feature(a.(*Feature), b.(*v1beta1.Feature), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Feature)(nil), (*Feature)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Feature_To_v1alpha1_Feature(a.(*v1beta1.Feature), b.(*Feature), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FeatureDeploymentInfo)(nil), (*v1beta1.FeatureDeploymentInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FeatureDeploymentInfo_To_v1beta1_FeatureDeploymentInfo(a.(*FeatureDeploymentInfo), b.(*v1beta1.FeatureDeploymentInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.FeatureDeploymentInfo)(nil), (*FeatureDeploymentInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FeatureDeploymentInfo_To_v1alpha1_FeatureDeploymentInfo(a.(*v1beta1.FeatureDeploymentInfo), b.(*FeatureDeploymentInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FeatureSummary)(nil), (*v1beta1.FeatureSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FeatureSummary_To_v1beta1_FeatureSummary(a.(*FeatureSummary), b.(*v1beta1.FeatureSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.FeatureSummary)(nil), (*FeatureSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FeatureSummary_To_v1alpha1_FeatureSummary(a.(*v1beta1.FeatureSummary), b.(*FeatureSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmChart)(nil), (*v1beta1.HelmChart)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HelmChart_To_v1beta1_HelmChart(a.(*HelmChart), b.(*v1beta1.HelmChart), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HelmChart)(nil), (*HelmChart)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HelmChart_To_v1alpha1_HelmChart(a.(*v1beta1.HelmChart), b.(*HelmChart), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmChartSummary)(nil), (*v1beta1.HelmChartSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HelmChartSummary_To_v1beta1_HelmChartSummary(a.(*HelmChartSummary), b.(*v1beta1.HelmChartSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HelmChartSummary)(nil), (*HelmChartSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HelmChartSummary_To_v1alpha1_HelmChartSummary(a.(*v1beta1.HelmChartSummary), b.(*HelmChartSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmInstallOptions)(nil), (*v1beta1.HelmInstallOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HelmInstallOptions_To_v1beta1_HelmInstallOptions(a.(*HelmInstallOptions), b.(*v1beta1.HelmInstallOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HelmInstallOptions)(nil), (*HelmInstallOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HelmInstallOptions_To_v1alpha1_HelmInstallOptions(a.(*v1beta1.HelmInstallOptions), b.(*HelmInstallOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmOptions)(nil), (*v1beta1.HelmOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HelmOptions_To_v1beta1_HelmOptions(a.(*HelmOptions), b.(*v1beta1.HelmOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HelmOptions)(nil), (*HelmOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HelmOptions_To_v1alpha1_HelmOptions(a.(*v1beta1.HelmOptions), b.(*HelmOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmUninstallOptions)(nil), (*v1beta1.HelmUninstallOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HelmUninstallOptions_To_v1beta1_HelmUninstallOptions(a.(*HelmUninstallOptions), b.(*v1beta1.HelmUninstallOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HelmUninstallOptions)(nil), (*HelmUninstallOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HelmUninstallOptions_To_v1alpha1_HelmUninstallOptions(a.(*v1beta1.HelmUninstallOptions), b.(*HelmUninstallOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmUpgradeOptions)(nil), (*v1beta1.HelmUpgradeOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HelmUpgradeOptions_To_v1beta1_HelmUpgradeOptions(a.(*HelmUpgradeOptions), b.(*v1beta1.HelmUpgradeOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HelmUpgradeOptions)(nil), (*HelmUpgradeOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HelmUpgradeOptions_To_v1alpha1_HelmUpgradeOptions(a.(*v1beta1.HelmUpgradeOptions), b.(*HelmUpgradeOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KustomizationRef)(nil), (*v1beta1.KustomizationRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KustomizationRef_To_v1beta1_KustomizationRef(a.(*KustomizationRef), b.(*v1beta1.KustomizationRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.KustomizationRef)(nil), (*KustomizationRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KustomizationRef_To_v1alpha1_KustomizationRef(a.(*v1beta1.KustomizationRef), b.(*KustomizationRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PolicyRef)(nil), (*v1beta1.PolicyRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PolicyRef_To_v1beta1_PolicyRef(a.(*PolicyRef), b.(*v1beta1.PolicyRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.PolicyRef)(nil), (*PolicyRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PolicyRef_To_v1alpha1_PolicyRef(a.(*v1beta1.PolicyRef), b.(*PolicyRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Profile)(nil), (*v1beta1.Profile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Profile_To_v1beta1_Profile(a.(*Profile), b.(*v1beta1.Profile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Profile)(nil), (*Profile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Profile_To_v1alpha1_Profile(a.(*v1beta1.Profile), b.(*Profile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProfileList)(nil), (*v1beta1.ProfileList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProfileList_To_v1beta1_ProfileList(a.(*ProfileList), b.(*v1beta1.ProfileList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ProfileList)(nil), (*ProfileList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ProfileList_To_v1alpha1_ProfileList(a.(*v1beta1.ProfileList), b.(*ProfileList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProfileResource)(nil), (*v1beta1.ProfileResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProfileResource_To_v1beta1_ProfileResource(a.(*ProfileResource), b.(*v1beta1.ProfileResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ProfileResource)(nil), (*ProfileResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ProfileResource_To_v1alpha1_ProfileResource(a.(*v1beta1.ProfileResource), b.(*ProfileResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseReport)(nil), (*v1beta1.ReleaseReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseReport_To_v1beta1_ReleaseReport(a.(*ReleaseReport), b.(*v1beta1.ReleaseReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ReleaseReport)(nil), (*ReleaseReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ReleaseReport_To_v1alpha1_ReleaseReport(a.(*v1beta1.ReleaseReport), b.(*ReleaseReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Resource)(nil), (*v1beta1.Resource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Resource_To_v1beta1_Resource(a.(*Resource), b.(*v1beta1.Resource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Resource)(nil), (*Resource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Resource_To_v1alpha1_Resource(a.(*v1beta1.Resource), b.(*Resource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceReport)(nil), (*v1beta1.ResourceReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceReport_To_v1beta1_ResourceReport(a.(*ResourceReport), b.(*v1beta1.ResourceReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ResourceReport)(nil), (*ResourceReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ResourceReport_To_v1alpha1_ResourceReport(a.(*v1beta1.ResourceReport), b.(*ResourceReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Spec)(nil), (*v1beta1.Spec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Spec_To_v1beta1_Spec(a.(*Spec), b.(*v1beta1.Spec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Spec)(nil), (*Spec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Spec_To_v1alpha1_Spec(a.(*v1beta1.Spec), b.(*Spec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Status)(nil), (*v1beta1.Status)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Status_To_v1beta1_Status(a.(*Status), b.(*v1beta1.Status), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Status)(nil), (*Status)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Status_To_v1alpha1_Status(a.(*v1beta1.Status), b.(*Status), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TemplateResourceRef)(nil), (*v1beta1.TemplateResourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TemplateResourceRef_To_v1beta1_TemplateResourceRef(a.(*TemplateResourceRef), b.(*v1beta1.TemplateResourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TemplateResourceRef)(nil), (*TemplateResourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TemplateResourceRef_To_v1alpha1_TemplateResourceRef(a.(*v1beta1.TemplateResourceRef), b.(*TemplateResourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ValidateHealth)(nil), (*v1beta1.ValidateHealth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ValidateHealth_To_v1beta1_ValidateHealth(a.(*ValidateHealth), b.(*v1beta1.ValidateHealth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ValidateHealth)(nil), (*ValidateHealth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ValidateHealth_To_v1alpha1_ValidateHealth(a.(*v1beta1.ValidateHealth), b.(*ValidateHealth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ValueFrom)(nil), (*v1beta1.ValueFrom)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ValueFrom_To_v1beta1_ValueFrom(a.(*ValueFrom), b.(*v1beta1.ValueFrom), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ValueFrom)(nil), (*ValueFrom)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ValueFrom_To_v1alpha1_ValueFrom(a.(*v1beta1.ValueFrom), b.(*ValueFrom), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Chart_To_v1beta1_Chart(in *Chart, out *v1beta1.Chart, s conversion.Scope) error {
	out.RepoURL = in.RepoURL
	out.ReleaseName = in.ReleaseName
	out.Namespace = in.Namespace
	out.ChartVersion = in.ChartVersion
	out.AppVersion = in.AppVersion
	out.Icon = in.Icon
	out.LastAppliedTime = (*v1.Time)(unsafe.Pointer(in.LastAppliedTime))
	return nil
}

// Convert_v1alpha1_Chart_To_v1beta1_Chart is an autogenerated conversion function.
func Convert_v1alpha1_Chart_To_v1beta1_Chart(in *Chart, out *v1beta1.Chart, s conversion.Scope) error {
	return autoConvert_v1alpha1_Chart_To_v1beta1_Chart(in, out, s)
}

func autoConvert_v1beta1_Chart_To_v1alpha1_Chart(in *v1beta1.Chart, out *Chart, s conversion.Scope) error {
	out.RepoURL = in.RepoURL
	out.ReleaseName = in.ReleaseName
	out.Namespace = in.Namespace
	out.ChartVersion = in.ChartVersion
	out.AppVersion = in.AppVersion
	out.Icon = in.Icon
	out.LastAppliedTime = (*v1.Time)(unsafe.Pointer(in.LastAppliedTime))
	return nil
}

// Convert_v1beta1_Chart_To_v1alpha1_Chart is an autogenerated conversion function.
func Convert_v1beta1_Chart_To_v1alpha1_Chart(in *v1beta1.Chart, out *Chart, s conversion.Scope) error {
	return autoConvert_v1beta1_Chart_To_v1alpha1_Chart(in, out, s)
}

func autoConvert_v1alpha1_ClusterConfiguration_To_v1beta1_ClusterConfiguration(in *ClusterConfiguration, out *v1beta1.ClusterConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterConfigurationStatus_To_v1beta1_ClusterConfigurationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterConfiguration_To_v1beta1_ClusterConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ClusterConfiguration_To_v1beta1_ClusterConfiguration(in *ClusterConfiguration, out *v1beta1.ClusterConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterConfiguration_To_v1beta1_ClusterConfiguration(in, out, s)
}

func autoConvert_v1beta1_ClusterConfiguration_To_v1alpha1_ClusterConfiguration(in *v1beta1.ClusterConfiguration, out *ClusterConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_ClusterConfigurationStatus_To_v1alpha1_ClusterConfigurationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ClusterConfiguration_To_v1alpha1_ClusterConfiguration is an autogenerated conversion function.
func Convert_v1beta1_ClusterConfiguration_To_v1alpha1_ClusterConfiguration(in *v1beta1.ClusterConfiguration, out *ClusterConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterConfiguration_To_v1alpha1_ClusterConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ClusterConfigurationList_To_v1beta1_ClusterConfigurationList(in *ClusterConfigurationList, out *v1beta1.ClusterConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.ClusterConfiguration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterConfigurationList_To_v1beta1_ClusterConfigurationList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterConfigurationList_To_v1beta1_ClusterConfigurationList(in *ClusterConfigurationList, out *v1beta1.ClusterConfigurationList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterConfigurationList_To_v1beta1_ClusterConfigurationList(in, out, s)
}

func autoConvert_v1beta1_ClusterConfigurationList_To_v1alpha1_ClusterConfigurationList(in *v1beta1.ClusterConfigurationList, out *ClusterConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ClusterConfiguration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_ClusterConfigurationList_To_v1alpha1_ClusterConfigurationList is an autogenerated conversion function.
func Convert_v1beta1_ClusterConfigurationList_To_v1alpha1_ClusterConfigurationList(in *v1beta1.ClusterConfigurationList, out *ClusterConfigurationList, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterConfigurationList_To_v1alpha1_ClusterConfigurationList(in, out, s)
}

func autoConvert_v1alpha1_ClusterConfigurationStatus_To_v1beta1_ClusterConfigurationStatus(in *ClusterConfigurationStatus, out *v1beta1.ClusterConfigurationStatus, s conversion.Scope) error {
	out.ClusterProfileResources = *(*[]v1beta1.ClusterProfileResource)(unsafe.Pointer(&in.ClusterProfileResources))
	out.ProfileResources = *(*[]v1beta1.ProfileResource)(unsafe.Pointer(&in.ProfileResources))
	return nil
}

// Convert_v1alpha1_ClusterConfigurationStatus_To_v1beta1_ClusterConfigurationStatus is an autogenerated conversion function.
func Convert_v1alpha1_ClusterConfigurationStatus_To_v1beta1_ClusterConfigurationStatus(in *ClusterConfigurationStatus, out *v1beta1.ClusterConfigurationStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterConfigurationStatus_To_v1beta1_ClusterConfigurationStatus(in, out, s)
}

func autoConvert_v1beta1_ClusterConfigurationStatus_To_v1alpha1_ClusterConfigurationStatus(in *v1beta1.ClusterConfigurationStatus, out *ClusterConfigurationStatus, s conversion.Scope) error {
	out.ClusterProfileResources = *(*[]ClusterProfileResource)(unsafe.Pointer(&in.ClusterProfileResources))
	out.ProfileResources = *(*[]ProfileResource)(unsafe.Pointer(&in.ProfileResources))
	return nil
}

// Convert_v1beta1_ClusterConfigurationStatus_To_v1alpha1_ClusterConfigurationStatus is an autogenerated conversion function.
func Convert_v1beta1_ClusterConfigurationStatus_To_v1alpha1_ClusterConfigurationStatus(in *v1beta1.ClusterConfigurationStatus, out *ClusterConfigurationStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterConfigurationStatus_To_v1alpha1_ClusterConfigurationStatus(in, out, s)
}

func autoConvert_v1alpha1_ClusterProfile_To_v1beta1_ClusterProfile(in *ClusterProfile, out *v1beta1.ClusterProfile, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_Spec_To_v1beta1_Spec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_Status_To_v1beta1_Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterProfile_To_v1beta1_ClusterProfile is an autogenerated conversion function.
func Convert_v1alpha1_ClusterProfile_To_v1beta1_ClusterProfile(in *ClusterProfile, out *v1beta1.ClusterProfile, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterProfile_To_v1beta1_ClusterProfile(in, out, s)
}

func autoConvert_v1beta1_ClusterProfile_To_v1alpha1_ClusterProfile(in *v1beta1.ClusterProfile, out *ClusterProfile, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_Spec_To_v1alpha1_Spec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_Status_To_v1alpha1_Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ClusterProfile_To_v1alpha1_ClusterProfile is an autogenerated conversion function.
func Convert_v1beta1_ClusterProfile_To_v1alpha1_ClusterProfile(in *v1beta1.ClusterProfile, out *ClusterProfile, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterProfile_To_v1alpha1_ClusterProfile(in, out, s)
}

func autoConvert_v1alpha1_ClusterProfileList_To_v1beta1_ClusterProfileList(in *ClusterProfileList, out *v1beta1.ClusterProfileList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.ClusterProfile, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ClusterProfile_To_v1beta1_ClusterProfile(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ClusterProfileList_To_v1beta1_ClusterProfileList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterProfileList_To_v1beta1_ClusterProfileList(in *ClusterProfileList, out *v1beta1.ClusterProfileList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterProfileList_To_v1beta1_ClusterProfileList(in, out, s)
}

func autoConvert_v1beta1_ClusterProfileList_To_v1alpha1_ClusterProfileList(in *v1beta1.ClusterProfileList, out *ClusterProfileList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterProfile, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_ClusterProfile_To_v1alpha1_ClusterProfile(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_ClusterProfileList_To_v1alpha1_ClusterProfileList is an autogenerated conversion function.
func Convert_v1beta1_ClusterProfileList_To_v1alpha1_ClusterProfileList(in *v1beta1.ClusterProfileList, out *ClusterProfileList, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterProfileList_To_v1alpha1_ClusterProfileList(in, out, s)
}

func autoConvert_v1alpha1_ClusterProfileResource_To_v1beta1_ClusterProfileResource(in *ClusterProfileResource, out *v1beta1.ClusterProfileResource, s conversion.Scope) error {
	out.ClusterProfileName = in.ClusterProfileName
	out.Features = *(*[]v1beta1.Feature)(unsafe.Pointer(&in.Features))
	return nil
}

// Convert_v1alpha1_ClusterProfileResource_To_v1beta1_ClusterProfileResource is an autogenerated conversion function.
func Convert_v1alpha1_ClusterProfileResource_To_v1beta1_ClusterProfileResource(in *ClusterProfileResource, out *v1beta1.ClusterProfileResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterProfileResource_To_v1beta1_ClusterProfileResource(in, out, s)
}

func autoConvert_v1beta1_ClusterProfileResource_To_v1alpha1_ClusterProfileResource(in *v1beta1.ClusterProfileResource, out *ClusterProfileResource, s conversion.Scope) error {
	out.ClusterProfileName = in.ClusterProfileName
	out.Features = *(*[]Feature)(unsafe.Pointer(&in.Features))
	return nil
}

// Convert_v1beta1_ClusterProfileResource_To_v1alpha1_ClusterProfileResource is an autogenerated conversion function.
func Convert_v1beta1_ClusterProfileResource_To_v1alpha1_ClusterProfileResource(in *v1beta1.ClusterProfileResource, out *ClusterProfileResource, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterProfileResource_To_v1alpha1_ClusterProfileResource(in, out, s)
}

func autoConvert_v1alpha1_ClusterReport_To_v1beta1_ClusterReport(in *ClusterReport, out *v1beta1.ClusterReport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterReportSpec_To_v1beta1_ClusterReportSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterReportStatus_To_v1beta1_ClusterReportStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterReport_To_v1beta1_ClusterReport is an autogenerated conversion function.
func Convert_v1alpha1_ClusterReport_To_v1beta1_ClusterReport(in *ClusterReport, out *v1beta1.ClusterReport, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterReport_To_v1beta1_ClusterReport(in, out, s)
}

func autoConvert_v1beta1_ClusterReport_To_v1alpha1_ClusterReport(in *v1beta1.ClusterReport, out *ClusterReport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_ClusterReportSpec_To_v1alpha1_ClusterReportSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_ClusterReportStatus_To_v1alpha1_ClusterReportStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ClusterReport_To_v1alpha1_ClusterReport is an autogenerated conversion function.
func Convert_v1beta1_ClusterReport_To_v1alpha1_ClusterReport(in *v1beta1.ClusterReport, out *ClusterReport, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterReport_To_v1alpha1_ClusterReport(in, out, s)
}

func autoConvert_v1alpha1_ClusterReportList_To_v1beta1_ClusterReportList(in *ClusterReportList, out *v1beta1.ClusterReportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.ClusterReport)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterReportList_To_v1beta1_ClusterReportList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterReportList_To_v1beta1_ClusterReportList(in *ClusterReportList, out *v1beta1.ClusterReportList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterReportList_To_v1beta1_ClusterReportList(in, out, s)
}

func autoConvert_v1beta1_ClusterReportList_To_v1alpha1_ClusterReportList(in *v1beta1.ClusterReportList, out *ClusterReportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ClusterReport)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_ClusterReportList_To_v1alpha1_ClusterReportList is an autogenerated conversion function.
func Convert_v1beta1_ClusterReportList_To_v1alpha1_ClusterReportList(in *v1beta1.ClusterReportList, out *ClusterReportList, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterReportList_To_v1alpha1_ClusterReportList(in, out, s)
}

func autoConvert_v1alpha1_ClusterReportSpec_To_v1beta1_ClusterReportSpec(in *ClusterReportSpec, out *v1beta1.ClusterReportSpec, s conversion.Scope) error {
	out.ClusterNamespace = in.ClusterNamespace
	out.ClusterName = in.ClusterName
	return nil
}

// Convert_v1alpha1_ClusterReportSpec_To_v1beta1_ClusterReportSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterReportSpec_To_v1beta1_ClusterReportSpec(in *ClusterReportSpec, out *v1beta1.ClusterReportSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterReportSpec_To_v1beta1_ClusterReportSpec(in, out, s)
}

func autoConvert_v1beta1_ClusterReportSpec_To_v1alpha1_ClusterReportSpec(in *v1beta1.ClusterReportSpec, out *ClusterReportSpec, s conversion.Scope) error {
	out.ClusterNamespace = in.ClusterNamespace
	out.ClusterName = in.ClusterName
	return nil
}

// Convert_v1beta1_ClusterReportSpec_To_v1alpha1_ClusterReportSpec is an autogenerated conversion function.
func Convert_v1beta1_ClusterReportSpec_To_v1alpha1_ClusterReportSpec(in *v1beta1.ClusterReportSpec, out *ClusterReportSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterReportSpec_To_v1alpha1_ClusterReportSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterReportStatus_To_v1beta1_ClusterReportStatus(in *ClusterReportStatus, out *v1beta1.ClusterReportStatus, s conversion.Scope) error {
	out.ReleaseReports = *(*[]v1beta1.ReleaseReport)(unsafe.Pointer(&in.ReleaseReports))
	out.ResourceReports = *(*[]v1beta1.ResourceReport)(unsafe.Pointer(&in.ResourceReports))
	out.KustomizeResourceReports = *(*[]v1beta1.ResourceReport)(unsafe.Pointer(&in.KustomizeResourceReports))
	return nil
}

// Convert_v1alpha1_ClusterReportStatus_To_v1beta1_ClusterReportStatus is an autogenerated conversion function.
func Convert_v1alpha1_ClusterReportStatus_To_v1beta1_ClusterReportStatus(in *ClusterReportStatus, out *v1beta1.ClusterReportStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterReportStatus_To_v1beta1_ClusterReportStatus(in, out, s)
}

func autoConvert_v1beta1_ClusterReportStatus_To_v1alpha1_ClusterReportStatus(in *v1beta1.ClusterReportStatus, out *ClusterReportStatus, s conversion.Scope) error {
	out.ReleaseReports = *(*[]ReleaseReport)(unsafe.Pointer(&in.ReleaseReports))
	out.ResourceReports = *(*[]ResourceReport)(unsafe.Pointer(&in.ResourceReports))
	out.KustomizeResourceReports = *(*[]ResourceReport)(unsafe.Pointer(&in.KustomizeResourceReports))
	return nil
}

// Convert_v1beta1_ClusterReportStatus_To_v1alpha1_ClusterReportStatus is an autogenerated conversion function.
func Convert_v1beta1_ClusterReportStatus_To_v1alpha1_ClusterReportStatus(in *v1beta1.ClusterReportStatus, out *ClusterReportStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterReportStatus_To_v1alpha1_ClusterReportStatus(in, out, s)
}

func autoConvert_v1alpha1_ClusterSummary_To_v1beta1_ClusterSummary(in *ClusterSummary, out *v1beta1.ClusterSummary, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterSummarySpec_To_v1beta1_ClusterSummarySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterSummaryStatus_To_v1beta1_ClusterSummaryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterSummary_To_v1beta1_ClusterSummary is an autogenerated conversion function.
func Convert_v1alpha1_ClusterSummary_To_v1beta1_ClusterSummary(in *ClusterSummary, out *v1beta1.ClusterSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterSummary_To_v1beta1_ClusterSummary(in, out, s)
}

func autoConvert_v1beta1_ClusterSummary_To_v1alpha1_ClusterSummary(in *v1beta1.ClusterSummary, out *ClusterSummary, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_ClusterSummarySpec_To_v1alpha1_ClusterSummarySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_ClusterSummaryStatus_To_v1alpha1_ClusterSummaryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ClusterSummary_To_v1alpha1_ClusterSummary is an autogenerated conversion function.
func Convert_v1beta1_ClusterSummary_To_v1alpha1_ClusterSummary(in *v1beta1.ClusterSummary, out *ClusterSummary, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterSummary_To_v1alpha1_ClusterSummary(in, out, s)
}

func autoConvert_v1alpha1_ClusterSummaryList_To_v1beta1_ClusterSummaryList(in *ClusterSummaryList, out *v1beta1.ClusterSummaryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.ClusterSummary, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ClusterSummary_To_v1beta1_ClusterSummary(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ClusterSummaryList_To_v1beta1_ClusterSummaryList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterSummaryList_To_v1beta1_ClusterSummaryList(in *ClusterSummaryList, out *v1beta1.ClusterSummaryList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterSummaryList_To_v1beta1_ClusterSummaryList(in, out, s)
}

func autoConvert_v1beta1_ClusterSummaryList_To_v1alpha1_ClusterSummaryList(in *v1beta1.ClusterSummaryList, out *ClusterSummaryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterSummary, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_ClusterSummary_To_v1alpha1_ClusterSummary(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_ClusterSummaryList_To_v1alpha1_ClusterSummaryList is an autogenerated conversion function.
func Convert_v1beta1_ClusterSummaryList_To_v1alpha1_ClusterSummaryList(in *v1beta1.ClusterSummaryList, out *ClusterSummaryList, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterSummaryList_To_v1alpha1_ClusterSummaryList(in, out, s)
}

func autoConvert_v1alpha1_ClusterSummarySpec_To_v1beta1_ClusterSummarySpec(in *ClusterSummarySpec, out *v1beta1.ClusterSummarySpec, s conversion.Scope) error {
	out.ClusterNamespace = in.ClusterNamespace
	out.ClusterName = in.ClusterName
	out.ClusterType = apiv1beta1.ClusterType(in.ClusterType)
	if err := Convert_v1alpha1_Spec_To_v1beta1_Spec(&in.ClusterProfileSpec, &out.ClusterProfileSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterSummarySpec_To_v1beta1_ClusterSummarySpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterSummarySpec_To_v1beta1_ClusterSummarySpec(in *ClusterSummarySpec, out *v1beta1.ClusterSummarySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterSummarySpec_To_v1beta1_ClusterSummarySpec(in, out, s)
}

func autoConvert_v1beta1_ClusterSummarySpec_To_v1alpha1_ClusterSummarySpec(in *v1beta1.ClusterSummarySpec, out *ClusterSummarySpec, s conversion.Scope) error {
	out.ClusterNamespace = in.ClusterNamespace
	out.ClusterName = in.ClusterName
	out.ClusterType = apiv1beta1.ClusterType(in.ClusterType)
	if err := Convert_v1beta1_Spec_To_v1alpha1_Spec(&in.ClusterProfileSpec, &out.ClusterProfileSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ClusterSummarySpec_To_v1alpha1_ClusterSummarySpec is an autogenerated conversion function.
func Convert_v1beta1_ClusterSummarySpec_To_v1alpha1_ClusterSummarySpec(in *v1beta1.ClusterSummarySpec, out *ClusterSummarySpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterSummarySpec_To_v1alpha1_ClusterSummarySpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterSummaryStatus_To_v1beta1_ClusterSummaryStatus(in *ClusterSummaryStatus, out *v1beta1.ClusterSummaryStatus, s conversion.Scope) error {
	out.Dependencies = (*string)(unsafe.Pointer(in.Dependencies))
	out.FeatureSummaries = *(*[]v1beta1.FeatureSummary)(unsafe.Pointer(&in.FeatureSummaries))
	out.DeployedGVKs = *(*[]v1beta1.FeatureDeploymentInfo)(unsafe.Pointer(&in.DeployedGVKs))
	out.HelmReleaseSummaries = *(*[]v1beta1.HelmChartSummary)(unsafe.Pointer(&in.HelmReleaseSummaries))
	return nil
}

// Convert_v1alpha1_ClusterSummaryStatus_To_v1beta1_ClusterSummaryStatus is an autogenerated conversion function.
func Convert_v1alpha1_ClusterSummaryStatus_To_v1beta1_ClusterSummaryStatus(in *ClusterSummaryStatus, out *v1beta1.ClusterSummaryStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterSummaryStatus_To_v1beta1_ClusterSummaryStatus(in, out, s)
}

func autoConvert_v1beta1_ClusterSummaryStatus_To_v1alpha1_ClusterSummaryStatus(in *v1beta1.ClusterSummaryStatus, out *ClusterSummaryStatus, s conversion.Scope) error {
	out.Dependencies = (*string)(unsafe.Pointer(in.Dependencies))
	out.FeatureSummaries = *(*[]FeatureSummary)(unsafe.Pointer(&in.FeatureSummaries))
	out.DeployedGVKs = *(*[]FeatureDeploymentInfo)(unsafe.Pointer(&in.DeployedGVKs))
	out.HelmReleaseSummaries = *(*[]HelmChartSummary)(unsafe.Pointer(&in.HelmReleaseSummaries))
	return nil
}

// Convert_v1beta1_ClusterSummaryStatus_To_v1alpha1_ClusterSummaryStatus is an autogenerated conversion function.
func Convert_v1beta1_ClusterSummaryStatus_To_v1alpha1_ClusterSummaryStatus(in *v1beta1.ClusterSummaryStatus, out *ClusterSummaryStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterSummaryStatus_To_v1alpha1_ClusterSummaryStatus(in, out, s)
}

func autoConvert_v1alpha1_Clusters_To_v1beta1_Clusters(in *Clusters, out *v1beta1.Clusters, s conversion.Scope) error {
	out.Hash = *(*[]byte)(unsafe.Pointer(&in.Hash))
	out.Clusters = *(*[]corev1.ObjectReference)(unsafe.Pointer(&in.Clusters))
	return nil
}

// Convert_v1alpha1_Clusters_To_v1beta1_Clusters is an autogenerated conversion function.
func Convert_v1alpha1_Clusters_To_v1beta1_Clusters(in *Clusters, out *v1beta1.Clusters, s conversion.Scope) error {
	return autoConvert_v1alpha1_Clusters_To_v1beta1_Clusters(in, out, s)
}

func autoConvert_v1beta1_Clusters_To_v1alpha1_Clusters(in *v1beta1.Clusters, out *Clusters, s conversion.Scope) error {
	out.Hash = *(*[]byte)(unsafe.Pointer(&in.Hash))
	out.Clusters = *(*[]corev1.ObjectReference)(unsafe.Pointer(&in.Clusters))
	return nil
}

// Convert_v1beta1_Clusters_To_v1alpha1_Clusters is an autogenerated conversion function.
func Convert_v1beta1_Clusters_To_v1alpha1_Clusters(in *v1beta1.Clusters, out *Clusters, s conversion.Scope) error {
	return autoConvert_v1beta1_Clusters_To_v1alpha1_Clusters(in, out, s)
}

func autoConvert_v1alpha1_DryRunReconciliationError_To_v1beta1_DryRunReconciliationError(in *DryRunReconciliationError, out *v1beta1.DryRunReconciliationError, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_DryRunReconciliationError_To_v1beta1_DryRunReconciliationError is an autogenerated conversion function.
func Convert_v1alpha1_DryRunReconciliationError_To_v1beta1_DryRunReconciliationError(in *DryRunReconciliationError, out *v1beta1.DryRunReconciliationError, s conversion.Scope) error {
	return autoConvert_v1alpha1_DryRunReconciliationError_To_v1beta1_DryRunReconciliationError(in, out, s)
}

func autoConvert_v1beta1_DryRunReconciliationError_To_v1alpha1_DryRunReconciliationError(in *v1beta1.DryRunReconciliationError, out *DryRunReconciliationError, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_DryRunReconciliationError_To_v1alpha1_DryRunReconciliationError is an autogenerated conversion function.
func Convert_v1beta1_DryRunReconciliationError_To_v1alpha1_DryRunReconciliationError(in *v1beta1.DryRunReconciliationError, out *DryRunReconciliationError, s conversion.Scope) error {
	return autoConvert_v1beta1_DryRunReconciliationError_To_v1alpha1_DryRunReconciliationError(in, out, s)
}

func autoConvert_v1alpha1_Feature_To_v1beta1_Feature(in *Feature, out *v1beta1.Feature, s conversion.Scope) error {
	out.FeatureID = v1beta1.FeatureID(in.FeatureID)
	out.Resources = *(*[]v1beta1.Resource)(unsafe.Pointer(&in.Resources))
	out.Charts = *(*[]v1beta1.Chart)(unsafe.Pointer(&in.Charts))
	return nil
}

// Convert_v1alpha1_Feature_To_v1beta1_Feature is an autogenerated conversion function.
func Convert_v1alpha1_Feature_To_v1beta1_Feature(in *Feature, out *v1beta1.Feature, s conversion.Scope) error {
	return autoConvert_v1alpha1_Feature_To_v1beta1_Feature(in, out, s)
}

func autoConvert_v1beta1_Feature_To_v1alpha1_Feature(in *v1beta1.Feature, out *Feature, s conversion.Scope) error {
	out.FeatureID = FeatureID(in.FeatureID)
	out.Resources = *(*[]Resource)(unsafe.Pointer(&in.Resources))
	out.Charts = *(*[]Chart)(unsafe.Pointer(&in.Charts))
	return nil
}

// Convert_v1beta1_Feature_To_v1alpha1_Feature is an autogenerated conversion function.
func Convert_v1beta1_Feature_To_v1alpha1_Feature(in *v1beta1.Feature, out *Feature, s conversion.Scope) error {
	return autoConvert_v1beta1_Feature_To_v1alpha1_Feature(in, out, s)
}

func autoConvert_v1alpha1_FeatureDeploymentInfo_To_v1beta1_FeatureDeploymentInfo(in *FeatureDeploymentInfo, out *v1beta1.FeatureDeploymentInfo, s conversion.Scope) error {
	out.FeatureID = v1beta1.FeatureID(in.FeatureID)
	out.DeployedGroupVersionKind = *(*[]string)(unsafe.Pointer(&in.DeployedGroupVersionKind))
	return nil
}

// Convert_v1alpha1_FeatureDeploymentInfo_To_v1beta1_FeatureDeploymentInfo is an autogenerated conversion function.
func Convert_v1alpha1_FeatureDeploymentInfo_To_v1beta1_FeatureDeploymentInfo(in *FeatureDeploymentInfo, out *v1beta1.FeatureDeploymentInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_FeatureDeploymentInfo_To_v1beta1_FeatureDeploymentInfo(in, out, s)
}

func autoConvert_v1beta1_FeatureDeploymentInfo_To_v1alpha1_FeatureDeploymentInfo(in *v1beta1.FeatureDeploymentInfo, out *FeatureDeploymentInfo, s conversion.Scope) error {
	out.FeatureID = FeatureID(in.FeatureID)
	out.DeployedGroupVersionKind = *(*[]string)(unsafe.Pointer(&in.DeployedGroupVersionKind))
	return nil
}

// Convert_v1beta1_FeatureDeploymentInfo_To_v1alpha1_FeatureDeploymentInfo is an autogenerated conversion function.
func Convert_v1beta1_FeatureDeploymentInfo_To_v1alpha1_FeatureDeploymentInfo(in *v1beta1.FeatureDeploymentInfo, out *FeatureDeploymentInfo, s conversion.Scope) error {
	return autoConvert_v1beta1_FeatureDeploymentInfo_To_v1alpha1_FeatureDeploymentInfo(in, out, s)
}

func autoConvert_v1alpha1_FeatureSummary_To_v1beta1_FeatureSummary(in *FeatureSummary, out *v1beta1.FeatureSummary, s conversion.Scope) error {
	out.FeatureID = v1beta1.FeatureID(in.FeatureID)
	out.Hash = *(*[]byte)(unsafe.Pointer(&in.Hash))
	out.Status = v1beta1.FeatureStatus(in.Status)
	out.FailureReason = (*string)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.DeployedGroupVersionKind = *(*[]string)(unsafe.Pointer(&in.DeployedGroupVersionKind))
	out.LastAppliedTime = (*v1.Time)(unsafe.Pointer(in.LastAppliedTime))
	return nil
}

// Convert_v1alpha1_FeatureSummary_To_v1beta1_FeatureSummary is an autogenerated conversion function.
func Convert_v1alpha1_FeatureSummary_To_v1beta1_FeatureSummary(in *FeatureSummary, out *v1beta1.FeatureSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_FeatureSummary_To_v1beta1_FeatureSummary(in, out, s)
}

func autoConvert_v1beta1_FeatureSummary_To_v1alpha1_FeatureSummary(in *v1beta1.FeatureSummary, out *FeatureSummary, s conversion.Scope) error {
	out.FeatureID = FeatureID(in.FeatureID)
	out.Hash = *(*[]byte)(unsafe.Pointer(&in.Hash))
	out.Status = FeatureStatus(in.Status)
	out.FailureReason = (*string)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.DeployedGroupVersionKind = *(*[]string)(unsafe.Pointer(&in.DeployedGroupVersionKind))
	out.LastAppliedTime = (*v1.Time)(unsafe.Pointer(in.LastAppliedTime))
	return nil
}

// Convert_v1beta1_FeatureSummary_To_v1alpha1_FeatureSummary is an autogenerated conversion function.
func Convert_v1beta1_FeatureSummary_To_v1alpha1_FeatureSummary(in *v1beta1.FeatureSummary, out *FeatureSummary, s conversion.Scope) error {
	return autoConvert_v1beta1_FeatureSummary_To_v1alpha1_FeatureSummary(in, out, s)
}

func autoConvert_v1alpha1_HelmChart_To_v1beta1_HelmChart(in *HelmChart, out *v1beta1.HelmChart, s conversion.Scope) error {
	out.RepositoryURL = in.RepositoryURL
	out.RepositoryName = in.RepositoryName
	out.ChartName = in.ChartName
	out.ChartVersion = in.ChartVersion
	out.ReleaseName = in.ReleaseName
	out.ReleaseNamespace = in.ReleaseNamespace
	out.Values = in.Values
	out.ValuesFrom = *(*[]v1beta1.ValueFrom)(unsafe.Pointer(&in.ValuesFrom))
	out.HelmChartAction = v1beta1.HelmChartAction(in.HelmChartAction)
	out.Options = (*v1beta1.HelmOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_v1alpha1_HelmChart_To_v1beta1_HelmChart is an autogenerated conversion function.
func Convert_v1alpha1_HelmChart_To_v1beta1_HelmChart(in *HelmChart, out *v1beta1.HelmChart, s conversion.Scope) error {
	return autoConvert_v1alpha1_HelmChart_To_v1beta1_HelmChart(in, out, s)
}

func autoConvert_v1beta1_HelmChart_To_v1alpha1_HelmChart(in *v1beta1.HelmChart, out *HelmChart, s conversion.Scope) error {
	out.RepositoryURL = in.RepositoryURL
	out.RepositoryName = in.RepositoryName
	out.ChartName = in.ChartName
	out.ChartVersion = in.ChartVersion
	out.ReleaseName = in.ReleaseName
	out.ReleaseNamespace = in.ReleaseNamespace
	out.Values = in.Values
	out.ValuesFrom = *(*[]ValueFrom)(unsafe.Pointer(&in.ValuesFrom))
	out.HelmChartAction = HelmChartAction(in.HelmChartAction)
	out.Options = (*HelmOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_v1beta1_HelmChart_To_v1alpha1_HelmChart is an autogenerated conversion function.
func Convert_v1beta1_HelmChart_To_v1alpha1_HelmChart(in *v1beta1.HelmChart, out *HelmChart, s conversion.Scope) error {
	return autoConvert_v1beta1_HelmChart_To_v1alpha1_HelmChart(in, out, s)
}

func autoConvert_v1alpha1_HelmChartSummary_To_v1beta1_HelmChartSummary(in *HelmChartSummary, out *v1beta1.HelmChartSummary, s conversion.Scope) error {
	out.ReleaseName = in.ReleaseName
	out.ReleaseNamespace = in.ReleaseNamespace
	out.Status = v1beta1.HelmChartStatus(in.Status)
	out.ValuesHash = *(*[]byte)(unsafe.Pointer(&in.ValuesHash))
	out.ConflictMessage = in.ConflictMessage
	return nil
}

// Convert_v1alpha1_HelmChartSummary_To_v1beta1_HelmChartSummary is an autogenerated conversion function.
func Convert_v1alpha1_HelmChartSummary_To_v1beta1_HelmChartSummary(in *HelmChartSummary, out *v1beta1.HelmChartSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_HelmChartSummary_To_v1beta1_HelmChartSummary(in, out, s)
}

func autoConvert_v1beta1_HelmChartSummary_To_v1alpha1_HelmChartSummary(in *v1beta1.HelmChartSummary, out *HelmChartSummary, s conversion.Scope) error {
	out.ReleaseName = in.ReleaseName
	out.ReleaseNamespace = in.ReleaseNamespace
	out.Status = HelmChartStatus(in.Status)
	out.ValuesHash = *(*[]byte)(unsafe.Pointer(&in.ValuesHash))
	out.ConflictMessage = in.ConflictMessage
	return nil
}

// Convert_v1beta1_HelmChartSummary_To_v1alpha1_HelmChartSummary is an autogenerated conversion function.
func Convert_v1beta1_HelmChartSummary_To_v1alpha1_HelmChartSummary(in *v1beta1.HelmChartSummary, out *HelmChartSummary, s conversion.Scope) error {
	return autoConvert_v1beta1_HelmChartSummary_To_v1alpha1_HelmChartSummary(in, out, s)
}

func autoConvert_v1alpha1_HelmInstallOptions_To_v1beta1_HelmInstallOptions(in *HelmInstallOptions, out *v1beta1.HelmInstallOptions, s conversion.Scope) error {
	out.CreateNamespace = in.CreateNamespace
	out.Replace = in.Replace
	return nil
}

// Convert_v1alpha1_HelmInstallOptions_To_v1beta1_HelmInstallOptions is an autogenerated conversion function.
func Convert_v1alpha1_HelmInstallOptions_To_v1beta1_HelmInstallOptions(in *HelmInstallOptions, out *v1beta1.HelmInstallOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_HelmInstallOptions_To_v1beta1_HelmInstallOptions(in, out, s)
}

func autoConvert_v1beta1_HelmInstallOptions_To_v1alpha1_HelmInstallOptions(in *v1beta1.HelmInstallOptions, out *HelmInstallOptions, s conversion.Scope) error {
	out.CreateNamespace = in.CreateNamespace
	out.Replace = in.Replace
	return nil
}

// Convert_v1beta1_HelmInstallOptions_To_v1alpha1_HelmInstallOptions is an autogenerated conversion function.
func Convert_v1beta1_HelmInstallOptions_To_v1alpha1_HelmInstallOptions(in *v1beta1.HelmInstallOptions, out *HelmInstallOptions, s conversion.Scope) error {
	return autoConvert_v1beta1_HelmInstallOptions_To_v1alpha1_HelmInstallOptions(in, out, s)
}

func autoConvert_v1alpha1_HelmOptions_To_v1beta1_HelmOptions(in *HelmOptions, out *v1beta1.HelmOptions, s conversion.Scope) error {
	out.SkipCRDs = in.SkipCRDs
	out.Wait = in.Wait
	out.WaitForJobs = in.WaitForJobs
	out.Timeout = (*v1.Duration)(unsafe.Pointer(in.Timeout))
	out.DisableHooks = in.DisableHooks
	out.DisableOpenAPIValidation = in.DisableOpenAPIValidation
	out.Atomic = in.Atomic
	out.DependencyUpdate = in.DependencyUpdate
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.EnableClientCache = in.EnableClientCache
	out.Description = in.Description
	if err := Convert_v1alpha1_HelmInstallOptions_To_v1beta1_HelmInstallOptions(&in.InstallOptions, &out.InstallOptions, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_HelmUpgradeOptions_To_v1beta1_HelmUpgradeOptions(&in.UpgradeOptions, &out.UpgradeOptions, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_HelmUninstallOptions_To_v1beta1_HelmUninstallOptions(&in.UninstallOptions, &out.UninstallOptions, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_HelmOptions_To_v1beta1_HelmOptions is an autogenerated conversion function.
func Convert_v1alpha1_HelmOptions_To_v1beta1_HelmOptions(in *HelmOptions, out *v1beta1.HelmOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_HelmOptions_To_v1beta1_HelmOptions(in, out, s)
}

func autoConvert_v1beta1_HelmOptions_To_v1alpha1_HelmOptions(in *v1beta1.HelmOptions, out *HelmOptions, s conversion.Scope) error {
	out.SkipCRDs = in.SkipCRDs
	out.Wait = in.Wait
	out.WaitForJobs = in.WaitForJobs
	out.Timeout = (*v1.Duration)(unsafe.Pointer(in.Timeout))
	out.DisableHooks = in.DisableHooks
	out.DisableOpenAPIValidation = in.DisableOpenAPIValidation
	out.Atomic = in.Atomic
	out.DependencyUpdate = in.DependencyUpdate
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.EnableClientCache = in.EnableClientCache
	out.Description = in.Description
	if err := Convert_v1beta1_HelmInstallOptions_To_v1alpha1_HelmInstallOptions(&in.InstallOptions, &out.InstallOptions, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_HelmUpgradeOptions_To_v1alpha1_HelmUpgradeOptions(&in.UpgradeOptions, &out.UpgradeOptions, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_HelmUninstallOptions_To_v1alpha1_HelmUninstallOptions(&in.UninstallOptions, &out.UninstallOptions, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_HelmOptions_To_v1alpha1_HelmOptions is an autogenerated conversion function.
func Convert_v1beta1_HelmOptions_To_v1alpha1_HelmOptions(in *v1beta1.HelmOptions, out *HelmOptions, s conversion.Scope) error {
	return autoConvert_v1beta1_HelmOptions_To_v1alpha1_HelmOptions(in, out, s)
}

func autoConvert_v1alpha1_HelmUninstallOptions_To_v1beta1_HelmUninstallOptions(in *HelmUninstallOptions, out *v1beta1.HelmUninstallOptions, s conversion.Scope) error {
	out.KeepHistory = in.KeepHistory
	out.DeletionPropagation = in.DeletionPropagation
	return nil
}

// Convert_v1alpha1_HelmUninstallOptions_To_v1beta1_HelmUninstallOptions is an autogenerated conversion function.
func Convert_v1alpha1_HelmUninstallOptions_To_v1beta1_HelmUninstallOptions(in *HelmUninstallOptions, out *v1beta1.HelmUninstallOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_HelmUninstallOptions_To_v1beta1_HelmUninstallOptions(in, out, s)
}

func autoConvert_v1beta1_HelmUninstallOptions_To_v1alpha1_HelmUninstallOptions(in *v1beta1.HelmUninstallOptions, out *HelmUninstallOptions, s conversion.Scope) error {
	out.KeepHistory = in.KeepHistory
	out.DeletionPropagation = in.DeletionPropagation
	return nil
}

// Convert_v1beta1_HelmUninstallOptions_To_v1alpha1_HelmUninstallOptions is an autogenerated conversion function.
func Convert_v1beta1_HelmUninstallOptions_To_v1alpha1_HelmUninstallOptions(in *v1beta1.HelmUninstallOptions, out *HelmUninstallOptions, s conversion.Scope) error {
	return autoConvert_v1beta1_HelmUninstallOptions_To_v1alpha1_HelmUninstallOptions(in, out, s)
}

func autoConvert_v1alpha1_HelmUpgradeOptions_To_v1beta1_HelmUpgradeOptions(in *HelmUpgradeOptions, out *v1beta1.HelmUpgradeOptions, s conversion.Scope) error {
	out.Force = in.Force
	out.ResetValues = in.ResetValues
	out.ReuseValues = in.ReuseValues
	out.ResetThenReuseValues = in.ResetThenReuseValues
	out.Recreate = in.Recreate
	out.MaxHistory = in.MaxHistory
	out.CleanupOnFail = in.CleanupOnFail
	out.SubNotes = in.SubNotes
	return nil
}

// Convert_v1alpha1_HelmUpgradeOptions_To_v1beta1_HelmUpgradeOptions is an autogenerated conversion function.
func Convert_v1alpha1_HelmUpgradeOptions_To_v1beta1_HelmUpgradeOptions(in *HelmUpgradeOptions, out *v1beta1.HelmUpgradeOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_HelmUpgradeOptions_To_v1beta1_HelmUpgradeOptions(in, out, s)
}

func autoConvert_v1beta1_HelmUpgradeOptions_To_v1alpha1_HelmUpgradeOptions(in *v1beta1.HelmUpgradeOptions, out *HelmUpgradeOptions, s conversion.Scope) error {
	out.Force = in.Force
	out.ResetValues = in.ResetValues
	out.ReuseValues = in.ReuseValues
	out.ResetThenReuseValues = in.ResetThenReuseValues
	out.Recreate = in.Recreate
	out.MaxHistory = in.MaxHistory
	out.CleanupOnFail = in.CleanupOnFail
	out.SubNotes = in.SubNotes
	return nil
}

// Convert_v1beta1_HelmUpgradeOptions_To_v1alpha1_HelmUpgradeOptions is an autogenerated conversion function.
func Convert_v1beta1_HelmUpgradeOptions_To_v1alpha1_HelmUpgradeOptions(in *v1beta1.HelmUpgradeOptions, out *HelmUpgradeOptions, s conversion.Scope) error {
	return autoConvert_v1beta1_HelmUpgradeOptions_To_v1alpha1_HelmUpgradeOptions(in, out, s)
}

func autoConvert_v1alpha1_KustomizationRef_To_v1beta1_KustomizationRef(in *KustomizationRef, out *v1beta1.KustomizationRef, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.Kind = in.Kind
	out.Path = in.Path
	out.TargetNamespace = in.TargetNamespace
	out.DeploymentType = v1beta1.DeploymentType(in.DeploymentType)
	out.Values = *(*map[string]string)(unsafe.Pointer(&in.Values))
	out.ValuesFrom = *(*[]v1beta1.ValueFrom)(unsafe.Pointer(&in.ValuesFrom))
	return nil
}

// Convert_v1alpha1_KustomizationRef_To_v1beta1_KustomizationRef is an autogenerated conversion function.
func Convert_v1alpha1_KustomizationRef_To_v1beta1_KustomizationRef(in *KustomizationRef, out *v1beta1.KustomizationRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_KustomizationRef_To_v1beta1_KustomizationRef(in, out, s)
}

func autoConvert_v1beta1_KustomizationRef_To_v1alpha1_KustomizationRef(in *v1beta1.KustomizationRef, out *KustomizationRef, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.Kind = in.Kind
	out.Path = in.Path
	out.TargetNamespace = in.TargetNamespace
	out.DeploymentType = DeploymentType(in.DeploymentType)
	out.Values = *(*map[string]string)(unsafe.Pointer(&in.Values))
	out.ValuesFrom = *(*[]ValueFrom)(unsafe.Pointer(&in.ValuesFrom))
	return nil
}

// Convert_v1beta1_KustomizationRef_To_v1alpha1_KustomizationRef is an autogenerated conversion function.
func Convert_v1beta1_KustomizationRef_To_v1alpha1_KustomizationRef(in *v1beta1.KustomizationRef, out *KustomizationRef, s conversion.Scope) error {
	return autoConvert_v1beta1_KustomizationRef_To_v1alpha1_KustomizationRef(in, out, s)
}

func autoConvert_v1alpha1_PolicyRef_To_v1beta1_PolicyRef(in *PolicyRef, out *v1beta1.PolicyRef, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.Kind = in.Kind
	out.Path = in.Path
	out.DeploymentType = v1beta1.DeploymentType(in.DeploymentType)
	return nil
}

// Convert_v1alpha1_PolicyRef_To_v1beta1_PolicyRef is an autogenerated conversion function.
func Convert_v1alpha1_PolicyRef_To_v1beta1_PolicyRef(in *PolicyRef, out *v1beta1.PolicyRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_PolicyRef_To_v1beta1_PolicyRef(in, out, s)
}

func autoConvert_v1beta1_PolicyRef_To_v1alpha1_PolicyRef(in *v1beta1.PolicyRef, out *PolicyRef, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.Kind = in.Kind
	out.Path = in.Path
	out.DeploymentType = DeploymentType(in.DeploymentType)
	return nil
}

// Convert_v1beta1_PolicyRef_To_v1alpha1_PolicyRef is an autogenerated conversion function.
func Convert_v1beta1_PolicyRef_To_v1alpha1_PolicyRef(in *v1beta1.PolicyRef, out *PolicyRef, s conversion.Scope) error {
	return autoConvert_v1beta1_PolicyRef_To_v1alpha1_PolicyRef(in, out, s)
}

func autoConvert_v1alpha1_Profile_To_v1beta1_Profile(in *Profile, out *v1beta1.Profile, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_Spec_To_v1beta1_Spec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_Status_To_v1beta1_Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Profile_To_v1beta1_Profile is an autogenerated conversion function.
func Convert_v1alpha1_Profile_To_v1beta1_Profile(in *Profile, out *v1beta1.Profile, s conversion.Scope) error {
	return autoConvert_v1alpha1_Profile_To_v1beta1_Profile(in, out, s)
}

func autoConvert_v1beta1_Profile_To_v1alpha1_Profile(in *v1beta1.Profile, out *Profile, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_Spec_To_v1alpha1_Spec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_Status_To_v1alpha1_Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Profile_To_v1alpha1_Profile is an autogenerated conversion function.
func Convert_v1beta1_Profile_To_v1alpha1_Profile(in *v1beta1.Profile, out *Profile, s conversion.Scope) error {
	return autoConvert_v1beta1_Profile_To_v1alpha1_Profile(in, out, s)
}

func autoConvert_v1alpha1_ProfileList_To_v1beta1_ProfileList(in *ProfileList, out *v1beta1.ProfileList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.Profile, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Profile_To_v1beta1_Profile(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ProfileList_To_v1beta1_ProfileList is an autogenerated conversion function.
func Convert_v1alpha1_ProfileList_To_v1beta1_ProfileList(in *ProfileList, out *v1beta1.ProfileList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProfileList_To_v1beta1_ProfileList(in, out, s)
}

func autoConvert_v1beta1_ProfileList_To_v1alpha1_ProfileList(in *v1beta1.ProfileList, out *ProfileList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Profile, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Profile_To_v1alpha1_Profile(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_ProfileList_To_v1alpha1_ProfileList is an autogenerated conversion function.
func Convert_v1beta1_ProfileList_To_v1alpha1_ProfileList(in *v1beta1.ProfileList, out *ProfileList, s conversion.Scope) error {
	return autoConvert_v1beta1_ProfileList_To_v1alpha1_ProfileList(in, out, s)
}

func autoConvert_v1alpha1_ProfileResource_To_v1beta1_ProfileResource(in *ProfileResource, out *v1beta1.ProfileResource, s conversion.Scope) error {
	out.ProfileName = in.ProfileName
	out.Features = *(*[]v1beta1.Feature)(unsafe.Pointer(&in.Features))
	return nil
}

// Convert_v1alpha1_ProfileResource_To_v1beta1_ProfileResource is an autogenerated conversion function.
func Convert_v1alpha1_ProfileResource_To_v1beta1_ProfileResource(in *ProfileResource, out *v1beta1.ProfileResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProfileResource_To_v1beta1_ProfileResource(in, out, s)
}

func autoConvert_v1beta1_ProfileResource_To_v1alpha1_ProfileResource(in *v1beta1.ProfileResource, out *ProfileResource, s conversion.Scope) error {
	out.ProfileName = in.ProfileName
	out.Features = *(*[]Feature)(unsafe.Pointer(&in.Features))
	return nil
}

// Convert_v1beta1_ProfileResource_To_v1alpha1_ProfileResource is an autogenerated conversion function.
func Convert_v1beta1_ProfileResource_To_v1alpha1_ProfileResource(in *v1beta1.ProfileResource, out *ProfileResource, s conversion.Scope) error {
	return autoConvert_v1beta1_ProfileResource_To_v1alpha1_ProfileResource(in, out, s)
}

func autoConvert_v1alpha1_ReleaseReport_To_v1beta1_ReleaseReport(in *ReleaseReport, out *v1beta1.ReleaseReport, s conversion.Scope) error {
	out.ReleaseName = in.ReleaseName
	out.ReleaseNamespace = in.ReleaseNamespace
	out.ChartVersion = in.ChartVersion
	out.Action = in.Action
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_ReleaseReport_To_v1beta1_ReleaseReport is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseReport_To_v1beta1_ReleaseReport(in *ReleaseReport, out *v1beta1.ReleaseReport, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseReport_To_v1beta1_ReleaseReport(in, out, s)
}

func autoConvert_v1beta1_ReleaseReport_To_v1alpha1_ReleaseReport(in *v1beta1.ReleaseReport, out *ReleaseReport, s conversion.Scope) error {
	out.ReleaseName = in.ReleaseName
	out.ReleaseNamespace = in.ReleaseNamespace
	out.ChartVersion = in.ChartVersion
	out.Action = in.Action
	out.Message = in.Message
	return nil
}

// Convert_v1beta1_ReleaseReport_To_v1alpha1_ReleaseReport is an autogenerated conversion function.
func Convert_v1beta1_ReleaseReport_To_v1alpha1_ReleaseReport(in *v1beta1.ReleaseReport, out *ReleaseReport, s conversion.Scope) error {
	return autoConvert_v1beta1_ReleaseReport_To_v1alpha1_ReleaseReport(in, out, s)
}

func autoConvert_v1alpha1_Resource_To_v1beta1_Resource(in *Resource, out *v1beta1.Resource, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Group = in.Group
	out.Kind = in.Kind
	out.Version = in.Version
	out.LastAppliedTime = (*v1.Time)(unsafe.Pointer(in.LastAppliedTime))
	out.Owner = in.Owner
	return nil
}

// Convert_v1alpha1_Resource_To_v1beta1_Resource is an autogenerated conversion function.
func Convert_v1alpha1_Resource_To_v1beta1_Resource(in *Resource, out *v1beta1.Resource, s conversion.Scope) error {
	return autoConvert_v1alpha1_Resource_To_v1beta1_Resource(in, out, s)
}

func autoConvert_v1beta1_Resource_To_v1alpha1_Resource(in *v1beta1.Resource, out *Resource, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Group = in.Group
	out.Kind = in.Kind
	out.Version = in.Version
	out.LastAppliedTime = (*v1.Time)(unsafe.Pointer(in.LastAppliedTime))
	out.Owner = in.Owner
	return nil
}

// Convert_v1beta1_Resource_To_v1alpha1_Resource is an autogenerated conversion function.
func Convert_v1beta1_Resource_To_v1alpha1_Resource(in *v1beta1.Resource, out *Resource, s conversion.Scope) error {
	return autoConvert_v1beta1_Resource_To_v1alpha1_Resource(in, out, s)
}

func autoConvert_v1alpha1_ResourceReport_To_v1beta1_ResourceReport(in *ResourceReport, out *v1beta1.ResourceReport, s conversion.Scope) error {
	if err := Convert_v1alpha1_Resource_To_v1beta1_Resource(&in.Resource, &out.Resource, s); err != nil {
		return err
	}
	out.Action = in.Action
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_ResourceReport_To_v1beta1_ResourceReport is an autogenerated conversion function.
func Convert_v1alpha1_ResourceReport_To_v1beta1_ResourceReport(in *ResourceReport, out *v1beta1.ResourceReport, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceReport_To_v1beta1_ResourceReport(in, out, s)
}

func autoConvert_v1beta1_ResourceReport_To_v1alpha1_ResourceReport(in *v1beta1.ResourceReport, out *ResourceReport, s conversion.Scope) error {
	if err := Convert_v1beta1_Resource_To_v1alpha1_Resource(&in.Resource, &out.Resource, s); err != nil {
		return err
	}
	out.Action = in.Action
	out.Message = in.Message
	return nil
}

// Convert_v1beta1_ResourceReport_To_v1alpha1_ResourceReport is an autogenerated conversion function.
func Convert_v1beta1_ResourceReport_To_v1alpha1_ResourceReport(in *v1beta1.ResourceReport, out *ResourceReport, s conversion.Scope) error {
	return autoConvert_v1beta1_ResourceReport_To_v1alpha1_ResourceReport(in, out, s)
}

func autoConvert_v1alpha1_Spec_To_v1beta1_Spec(in *Spec, out *v1beta1.Spec, s conversion.Scope) error {
	// WARNING: in.ClusterSelector requires manual conversion: inconvertible types (github.com/projectsveltos/libsveltos/api/v1alpha1.Selector vs github.com/projectsveltos/libsveltos/api/v1beta1.Selector)
	out.ClusterRefs = *(*[]corev1.ObjectReference)(unsafe.Pointer(&in.ClusterRefs))
	out.SetRefs = *(*[]string)(unsafe.Pointer(&in.SetRefs))
	out.SyncMode = v1beta1.SyncMode(in.SyncMode)
	out.Tier = in.Tier
	out.ContinueOnConflict = in.ContinueOnConflict
	out.MaxUpdate = (*intstr.IntOrString)(unsafe.Pointer(in.MaxUpdate))
	out.StopMatchingBehavior = v1beta1.StopMatchingBehavior(in.StopMatchingBehavior)
	out.Reloader = in.Reloader
	out.TemplateResourceRefs = *(*[]v1beta1.TemplateResourceRef)(unsafe.Pointer(&in.TemplateResourceRefs))
	out.DependsOn = *(*[]string)(unsafe.Pointer(&in.DependsOn))
	out.PolicyRefs = *(*[]v1beta1.PolicyRef)(unsafe.Pointer(&in.PolicyRefs))
	out.HelmCharts = *(*[]v1beta1.HelmChart)(unsafe.Pointer(&in.HelmCharts))
	out.KustomizationRefs = *(*[]v1beta1.KustomizationRef)(unsafe.Pointer(&in.KustomizationRefs))
	out.ValidateHealths = *(*[]v1beta1.ValidateHealth)(unsafe.Pointer(&in.ValidateHealths))
	out.ExtraLabels = *(*map[string]string)(unsafe.Pointer(&in.ExtraLabels))
	out.ExtraAnnotations = *(*map[string]string)(unsafe.Pointer(&in.ExtraAnnotations))
	return nil
}

func autoConvert_v1beta1_Spec_To_v1alpha1_Spec(in *v1beta1.Spec, out *Spec, s conversion.Scope) error {
	// WARNING: in.ClusterSelector requires manual conversion: inconvertible types (github.com/projectsveltos/libsveltos/api/v1beta1.Selector vs github.com/projectsveltos/libsveltos/api/v1alpha1.Selector)
	out.ClusterRefs = *(*[]corev1.ObjectReference)(unsafe.Pointer(&in.ClusterRefs))
	out.SetRefs = *(*[]string)(unsafe.Pointer(&in.SetRefs))
	out.SyncMode = SyncMode(in.SyncMode)
	out.Tier = in.Tier
	out.ContinueOnConflict = in.ContinueOnConflict
	out.MaxUpdate = (*intstr.IntOrString)(unsafe.Pointer(in.MaxUpdate))
	out.StopMatchingBehavior = StopMatchingBehavior(in.StopMatchingBehavior)
	out.Reloader = in.Reloader
	out.TemplateResourceRefs = *(*[]TemplateResourceRef)(unsafe.Pointer(&in.TemplateResourceRefs))
	out.DependsOn = *(*[]string)(unsafe.Pointer(&in.DependsOn))
	out.PolicyRefs = *(*[]PolicyRef)(unsafe.Pointer(&in.PolicyRefs))
	out.HelmCharts = *(*[]HelmChart)(unsafe.Pointer(&in.HelmCharts))
	out.KustomizationRefs = *(*[]KustomizationRef)(unsafe.Pointer(&in.KustomizationRefs))
	out.ValidateHealths = *(*[]ValidateHealth)(unsafe.Pointer(&in.ValidateHealths))
	out.ExtraLabels = *(*map[string]string)(unsafe.Pointer(&in.ExtraLabels))
	out.ExtraAnnotations = *(*map[string]string)(unsafe.Pointer(&in.ExtraAnnotations))
	return nil
}

func autoConvert_v1alpha1_Status_To_v1beta1_Status(in *Status, out *v1beta1.Status, s conversion.Scope) error {
	out.MatchingClusterRefs = *(*[]corev1.ObjectReference)(unsafe.Pointer(&in.MatchingClusterRefs))
	if err := Convert_v1alpha1_Clusters_To_v1beta1_Clusters(&in.UpdatingClusters, &out.UpdatingClusters, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_Clusters_To_v1beta1_Clusters(&in.UpdatedClusters, &out.UpdatedClusters, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Status_To_v1beta1_Status is an autogenerated conversion function.
func Convert_v1alpha1_Status_To_v1beta1_Status(in *Status, out *v1beta1.Status, s conversion.Scope) error {
	return autoConvert_v1alpha1_Status_To_v1beta1_Status(in, out, s)
}

func autoConvert_v1beta1_Status_To_v1alpha1_Status(in *v1beta1.Status, out *Status, s conversion.Scope) error {
	out.MatchingClusterRefs = *(*[]corev1.ObjectReference)(unsafe.Pointer(&in.MatchingClusterRefs))
	if err := Convert_v1beta1_Clusters_To_v1alpha1_Clusters(&in.UpdatingClusters, &out.UpdatingClusters, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_Clusters_To_v1alpha1_Clusters(&in.UpdatedClusters, &out.UpdatedClusters, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Status_To_v1alpha1_Status is an autogenerated conversion function.
func Convert_v1beta1_Status_To_v1alpha1_Status(in *v1beta1.Status, out *Status, s conversion.Scope) error {
	return autoConvert_v1beta1_Status_To_v1alpha1_Status(in, out, s)
}

func autoConvert_v1alpha1_TemplateResourceRef_To_v1beta1_TemplateResourceRef(in *TemplateResourceRef, out *v1beta1.TemplateResourceRef, s conversion.Scope) error {
	out.Resource = in.Resource
	out.Identifier = in.Identifier
	return nil
}

// Convert_v1alpha1_TemplateResourceRef_To_v1beta1_TemplateResourceRef is an autogenerated conversion function.
func Convert_v1alpha1_TemplateResourceRef_To_v1beta1_TemplateResourceRef(in *TemplateResourceRef, out *v1beta1.TemplateResourceRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_TemplateResourceRef_To_v1beta1_TemplateResourceRef(in, out, s)
}

func autoConvert_v1beta1_TemplateResourceRef_To_v1alpha1_TemplateResourceRef(in *v1beta1.TemplateResourceRef, out *TemplateResourceRef, s conversion.Scope) error {
	out.Resource = in.Resource
	out.Identifier = in.Identifier
	return nil
}

// Convert_v1beta1_TemplateResourceRef_To_v1alpha1_TemplateResourceRef is an autogenerated conversion function.
func Convert_v1beta1_TemplateResourceRef_To_v1alpha1_TemplateResourceRef(in *v1beta1.TemplateResourceRef, out *TemplateResourceRef, s conversion.Scope) error {
	return autoConvert_v1beta1_TemplateResourceRef_To_v1alpha1_TemplateResourceRef(in, out, s)
}

func autoConvert_v1alpha1_ValidateHealth_To_v1beta1_ValidateHealth(in *ValidateHealth, out *v1beta1.ValidateHealth, s conversion.Scope) error {
	out.Name = in.Name
	out.FeatureID = v1beta1.FeatureID(in.FeatureID)
	out.Group = in.Group
	out.Version = in.Version
	out.Kind = in.Kind
	out.LabelFilters = *(*[]apiv1beta1.LabelFilter)(unsafe.Pointer(&in.LabelFilters))
	out.Namespace = in.Namespace
	out.Script = in.Script
	return nil
}

// Convert_v1alpha1_ValidateHealth_To_v1beta1_ValidateHealth is an autogenerated conversion function.
func Convert_v1alpha1_ValidateHealth_To_v1beta1_ValidateHealth(in *ValidateHealth, out *v1beta1.ValidateHealth, s conversion.Scope) error {
	return autoConvert_v1alpha1_ValidateHealth_To_v1beta1_ValidateHealth(in, out, s)
}

func autoConvert_v1beta1_ValidateHealth_To_v1alpha1_ValidateHealth(in *v1beta1.ValidateHealth, out *ValidateHealth, s conversion.Scope) error {
	out.Name = in.Name
	out.FeatureID = FeatureID(in.FeatureID)
	out.Group = in.Group
	out.Version = in.Version
	out.Kind = in.Kind
	out.LabelFilters = *(*[]apiv1alpha1.LabelFilter)(unsafe.Pointer(&in.LabelFilters))
	out.Namespace = in.Namespace
	out.Script = in.Script
	return nil
}

// Convert_v1beta1_ValidateHealth_To_v1alpha1_ValidateHealth is an autogenerated conversion function.
func Convert_v1beta1_ValidateHealth_To_v1alpha1_ValidateHealth(in *v1beta1.ValidateHealth, out *ValidateHealth, s conversion.Scope) error {
	return autoConvert_v1beta1_ValidateHealth_To_v1alpha1_ValidateHealth(in, out, s)
}

func autoConvert_v1alpha1_ValueFrom_To_v1beta1_ValueFrom(in *ValueFrom, out *v1beta1.ValueFrom, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.Kind = in.Kind
	return nil
}

// Convert_v1alpha1_ValueFrom_To_v1beta1_ValueFrom is an autogenerated conversion function.
func Convert_v1alpha1_ValueFrom_To_v1beta1_ValueFrom(in *ValueFrom, out *v1beta1.ValueFrom, s conversion.Scope) error {
	return autoConvert_v1alpha1_ValueFrom_To_v1beta1_ValueFrom(in, out, s)
}

func autoConvert_v1beta1_ValueFrom_To_v1alpha1_ValueFrom(in *v1beta1.ValueFrom, out *ValueFrom, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.Kind = in.Kind
	return nil
}

// Convert_v1beta1_ValueFrom_To_v1alpha1_ValueFrom is an autogenerated conversion function.
func Convert_v1beta1_ValueFrom_To_v1alpha1_ValueFrom(in *v1beta1.ValueFrom, out *ValueFrom, s conversion.Scope) error {
	return autoConvert_v1beta1_ValueFrom_To_v1alpha1_ValueFrom(in, out, s)
}
