apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile 
metadata: 
  name: kubevela-core
spec:
  clusterSelector:
    matchLabels:
      env: production
  syncMode: Continuous
  helmCharts:
  - repositoryURL: https://kubevela.github.io/charts
    repositoryName: kubevela
    chartName: kubevela/vela-core
    chartVersion: 1.10.4
    releaseName: kubevela-core-latest
    releaseNamespace: vela-system
    helmChartAction: Install
