# This shows how to deploy Kyverno and Nginx in any cluster
# matching label selector env=fv
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: multiple-helm-charts
spec:
  clusterSelector:
    matchLabels:
      env: prod
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    https://helm.nginx.com/stable/
    repositoryName:   nginx-stable
    chartName:        nginx-stable/nginx-ingress
    chartVersion:     1.4.1
    releaseName:      ngix-latest
    releaseNamespace: nginx
    helmChartAction:  Install
    values: |
      controller:
        nginxStatus:
          allowCidrs: {{ index .Cluster.spec.clusterNetwork.pods.cidrBlocks 0 }}
  - repositoryURL:    https://kyverno.github.io/kyverno/
    repositoryName:   kyverno
    chartName:        kyverno/kyverno
    chartVersion:     3.3.2
    releaseName:      kyverno-latest
    releaseNamespace: kyverno
    helmChartAction:  Install
    values: |
      admissionController:
        replicas: 3"