apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: nats
spec:
  clusterSelector:
    matchLabels:
      env: fv
  helmCharts:
  - repositoryURL:    https://nats-io.github.io/k8s/helm/charts/
    repositoryName:   nats
    chartName:        nats/nats
    chartVersion:     1.2.10
    releaseName:      nats
    releaseNamespace: nats
    helmChartAction:  Install
