//go:build ignore
// +build ignore

/*
Copyright 2026. projectsveltos.io. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const (
	crdTemplate = `// Generated by *go generate* - DO NOT EDIT
/*
Copyright 2026. projectsveltos.io. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package crd

var {{ .ExportedVar }}File = {{ printf "%q" .File }}
var {{ .ExportedVar }}CRD = []byte({{- printf "%s" .CRD -}})
`
)

func generate(filename, outputFilename, crdName string) {
	// Get CustomResourceDefinition file
	fileAbs, err := filepath.Abs(filename)
	if err != nil {
		panic(err)
	}

	content, err := os.ReadFile(fileAbs)
	if err != nil {
		panic(err)
	}
	// CRD descriptions can contain backticks (markdown code formatting), which a raw
	// string literal cannot represent directly. Close the raw string, splice in a quoted
	// backtick, then reopen the raw string.
	escaped := strings.ReplaceAll(string(content), "`", "` + \"`\" + `")
	contentStr := "`" + escaped + "`"

	// Find the output.
	f, err := os.Create(outputFilename + ".go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	// Store file contents.
	type Info struct {
		CRD         string
		File        string
		ExportedVar string
	}
	mi := Info{
		CRD:         contentStr,
		File:        filename,
		ExportedVar: crdName,
	}

	// Generate template.
	crdTmpl := template.Must(template.New("crd-generate").Parse(crdTemplate))
	if err := crdTmpl.Execute(f, mi); err != nil {
		panic(err)
	}
}

func main() {
	clusterProfileFile := "../../config/crd/bases/config.projectsveltos.io_clusterprofiles.yaml"
	generate(clusterProfileFile, "clusterprofiles", "ClusterProfile")

	profileFile := "../../config/crd/bases/config.projectsveltos.io_profiles.yaml"
	generate(profileFile, "profiles", "Profile")

	clusterSummaryFile := "../../config/crd/bases/config.projectsveltos.io_clustersummaries.yaml"
	generate(clusterSummaryFile, "clustersummaries", "ClusterSummary")

	clusterConfigurationFile := "../../config/crd/bases/config.projectsveltos.io_clusterconfigurations.yaml"
	generate(clusterConfigurationFile, "clusterconfigurations", "ClusterConfiguration")

	clusterReportFile := "../../config/crd/bases/config.projectsveltos.io_clusterreports.yaml"
	generate(clusterReportFile, "clusterreports", "ClusterReport")

	clusterPromotionFile := "../../config/crd/bases/config.projectsveltos.io_clusterpromotions.yaml"
	generate(clusterPromotionFile, "clusterpromotions", "ClusterPromotion")
}
